project:
  type: website
  output-dir: docs
  preview: 
    port: 5556
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "Kazuharu Yanagimoto"
  favicon: static/img/favicon.drawio.svg
  site-url: https://kazuyanagimoto.com
  repo-url: https://github.com/kazuyanagimoto/kazuyanagimoto.github.io
  google-analytics: "G-EX523L4LWJ"
  twitter-card:
    creator: "@kazuyanagimoto"
    site: "@kazuyanagimoto"
  navbar:
    right:
      - text: About
        file: about/index.qmd
      - text: Research
        file: research/index.qmd
      - text: Blog
        file: blog/index.qmd
      - text: CV
        href: https://kazuyanagimoto.com/cv/cv.pdf
      - text: Talks
        file: talks/index.qmd
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Kazuharu Yanagimoto</span>
      <span class="faux-block">All content licensed under</span>
      <span class="faux-block">[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} Creative Commons CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)</span>
    center: |
      <span class="faux-block">[{{< fa brands github >}}]({{< var github-url >}}) [{{< fa brands twitter >}}]({{< var twitter-url >}}) [{{< fa brands linkedin >}}]({{< var linkedin-url >}})</span>
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">View the source at [{{< fa brands github >}} GitHub]({{< var repo-url >}})</span>
      
format:
  html:
    theme: 
      - static/html/custom.scss

bibliography: references.bib




