project:
  type: website
  output-dir: docs
  preview: 
    port: 5556
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "Kazuharu Yanagimoto"
  site-url: https://kazuyanagimoto.com
  repo-url: https://github.com/kazuyanagimoto/kazuyanagimoto.github.io
  google-analytics: "G-EX523L4LWJ"
  twitter-card:
    creator: "@kazuyanagimoto"
    site: "@kazuyanagimoto"
  navbar:
    right:
      - text: About
        file: about/index.qmd
      - text: Blog
        file: blog/index.qmd
      - text: CV
        href: https://kazuyanagimoto.com/cv/
      - text: Talks
        file: talks/index.qmd
      - icon: github
        href: https://github.com/kazuyanagimoto
      - icon: twitter
        href: https://twitter.com/kazuyanagimoto
      - icon: linkedin
        href: https://www.linkedin.com/in/kazuharu-yanagimoto/
      
format:
  html:
    theme: 
      - static/html/custom.scss



