[build]
command = 'hugo'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.98.0'


[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'


[[redirects]]
  from = "https://kazuyanagimoto.netlify.app/"
  to = "https://kazuyanagimoto.com"
  status = 301
  force = true