---
title: A Quantitative Model of Non-Marriage and Fertility
subtitle: Bargaining over Leisure
date: 2024-08-29
date-modified: last-modified
author:
  - name: Kazuharu Yanagimoto
    url: "{{< var website-url >}}"
    orcid: "{{< var orcid >}}"
    affiliation: "{{< var affiliation >}}"
    email: "{{< var email >}}"
categories:
  - Marriage
  - Fertility
  - Japan
image: thumbnail.svg
status: working-papers
feature: true
pub-info:
  links:
    - name: Latest WP
      url: https://arxiv.org/abs/2603.14758
      icon: ai ai-arxiv
    - name: Slides
      url: "cigs_yanagimoto.pdf"
      local: true
      icon: fa-solid fa-chalkboard-user
pub-status: 
  status: Writing
  class: warning
  icon: fa-solid fa-pencil
#   status: Under review
#   class: success
#   icon: fas fa-glasses
---

## Abstract

This paper introduces a new factor contributing to the decline in marriage and fertility: the growth of leisure technology. Over recent decades, high-income countries have experienced two notable shifts in household and family dynamics. First, there has been a significant decline in marriage rates and fertility. Second, time has increasingly been allocated to leisure activities. This paper presents a unified model of marriage and fertility, incorporating intra-household bargaining dynamics. The model, calibrated using data from Japan between 2019 and 2023, is employed to assess the impact of leisure technology growth on marriage and fertility during 2005-2009. The findings highlight that leisure technology growth makes single life relatively more appealing compared to marriage and parenthood. The model explains 21.1% of the decline in marriage and 73.1% of the decrease in fertility.

## Slides

```{=html}
<iframe class="slide-deck" src="cigs_yanagimoto.html"></iframe>
```

## BibTeX citation

```bibtex
@misc{yanagimoto2026,
  title = {A Quantitative Model of Non-Marriage and Fertility: Bargaining over Leisure},
  author = {Yanagimoto, Kazuharu},
  year = {2026},
  eprint = {2603.14758},
  archiveprefix = {arXiv},
  doi = {10.48550/arXiv.2603.14758}
}
```