---
title: "Why not Choose a Better Job? Flexibility, Social Norms, and Gender Gaps in Japan"
date: 2023-01-20
author:
  - name: Kazuharu Yanagimoto
    url: https://kazuyanagimoto.com/
    orcid: 0009-0007-1967-8304
    affiliation: CEMFI
categories:
  - Gender Gaps
  - Social Norms
  - Japan
pub-info:
  links:
    - name: Slides (SAEe2022)
      url: yanagimoto-why.html
      local: true
      icon: fa-solid fa-chalkboard-user
    - name: Slides (SAEe2022)
      url: yanagimoto-why_slides.pdf
      local: true
      icon: fa-solid fa-file-pdf
  extra: >-
    Presented at 47th Simposio de la Asociación Española de Economía (Valencia, December 15-17, 2022)
pub-status: 
  status: Writing
  class: warning
  icon: fa-solid fa-pencil
#   status: Under review
#   class: success
#   icon: fas fa-glasses
---

## Important links

- Paper (will be uploaded soon)
- [Slides (SAEe2022)](yanagimoto-why.html)
- [PDF Slides (SAEe2022)](yanagimoto-why_slides.pdf)

## Abstract

Japan ranks 116th out of 146 countries in the World Economic Forum’s Global Gender Gap Index 2022, well below many developing countries, and has one of the largest gender pay gaps among high-income countries. On the other hand, women’s labor force participation is high in Japan. However, women are much more likely to work in non-regular jobs, which are associated with lower wages and fewer hours. Men, in contrast, have regular, higher-paid jobs with long-hours requirements. In this paper, I build and estimate a model in which couples jointly decide their occupations and working hours. Occupations differ in their flexibility. Regular ones require long working hours, and hourly wages are convex functions of hours worked. Non-regular occupations have a linear mapping between hours worked and hourly wages. The model also allows for social norms that penalize women who earn more than their husbands. Given the inflexibility of regular jobs and social norms, women are more likely to choose non-regular jobs or not to work, and allocate a larger share of their hours for home production for their households. The model can account for all the observed gender gaps in labor force participation, 33% in occupational choices, 74% in labor hours, and 34% in wages. Through the lens of the model, the inflexibility of regular jobs explains almost all the gaps in occupational choices and wages, while social norms that penalize women who earn more than their husbands account for all the gap in the participation rate and half of the gap in hours worked.


## BibTeX citation

```bibtex
@unpublished{Yanagimoto:2023,
    Author = {Kazuharu Yanagimoto},
    Note = {Working paper},
    Title = {Why not Choose a Better Job? Flexibility, Social Norms, and Gender Gaps in Japan},
    Year = {2023}}
```