---
title: "Why not Choose a Better Job?"
subtitle: "Flexibility, Social Norms, and Gender Gaps in Japan"
date: 2023-01-20
date-modified: last-modified
author:
  - name: Kazuharu Yanagimoto
    url: {{< var website-url >}}
    orcid: {{ < var orcid >}}
    affiliation: CEMFI
categories:
  - Gender Gaps
  - Social Norms
  - Japan
image: thumbnail.svg
status: working-papers
pub-info:
  links:
    - name: Latest WP
      url: "yanagimoto_common_cheetah.pdf"
      local: true
      icon: fa-regular fa-file-pdf
    - name: CEMFI WP
      url: https://www.cemfi.es/ftp/wp/2405.pdf
      icon: fa-solid fa-file-pdf
    - name: Slides (SEHO2023)
      url: "seho2023_yanagimoto.pdf"
      local: true
      icon: fa-solid fa-chalkboard-user
  extra: >-
    Presented at 47th Simposio de la Asociación Española de Economía (Valencia, December 15-17, 2022) and Society of Economics of the Household (SEHO) meeting (Copenhagen, June 2023)
pub-status: 
  status: Writing
  class: warning
  icon: fa-solid fa-pencil
#   status: Under review
#   class: success
#   icon: fas fa-glasses
---


## Abstract

Japan ranks 125th out of 146 countries in the World Economic Forum’s Global Gender Gap Index 2023, well below many developed countries, and has one of the largest gender pay gaps among high-income countries. On the other hand, women’s labor force participation is high in Japan. However, women are much more likely to work in non-regular jobs, which are associated with lower wages and fewer hours. Men, in contrast, have regular, higher-paid jobs with long-hours requirements. In this paper, I build and estimate a model where couples jointly decide their occupations and working hours. Occupations differ in their flexibility. Regular jobs require long working hours, and hourly wages are a convex function of hours worked. Non-regular occupations have a linear mapping between hours worked and hourly wages. The model also allows for social norms that penalize women who earn more than their husbands.Given the inflexibility of regular jobs and social norms, women are more likely to choose non-regular jobs or not to work, and allocate a larger share of their hours for home production. The model can account for nearly all gaps in participation rates, occupational choices, and labor hours, along with 22.4% of the wage gap. Through the lens of the model, the inflexibility of regular jobs explains almost all the gaps in occupational choices and wages, while social norms that penalize women who earn more than their husbands account for all of the gap in the participation rate and half of the gap in hours worked.

## Slides

```{=html}
<iframe class="slide-deck" src="seho2023_yanagimoto.html"></iframe>
```

## BibTeX citation

```bibtex
@unpublished{yanagimoto2024,
    Title = {Why not Choose a Better Job?
             Flexibility, Social Norms, and Gender Gaps in Japan},
    Author = {Kazuharu Yanagimoto},
    Note = {Working paper},
    Year = {2024},
    month = mar,
    series = {CEMFI Working Paper},
    number = {2405},
}
```
